name: project_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  file_picker: ^10.2.0
  video_player: ^2.10.0
  chewie: ^1.11.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  fl_chart: ^1.0.0
  firebase_app_check: ^0.3.2+7
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  android_path_provider: ^0.3.1
  photo_view: ^0.15.0
  transparent_image: ^2.0.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

